"""Emit the numbers the manuscripts quote in prose as LaTeX macros.

Tables are generated, but sentences like "the proposed pipeline reaches an AUPRC
of X" also carry numbers, and those are exactly the ones that rot when an
experiment is rerun. Writing them as macros means the prose is regenerated with
the tables and cannot drift from the results.

A macro that has no value yet expands to a visible placeholder rather than
failing to compile, so a partially finished study still produces a readable
draft.
"""

from __future__ import annotations

from pathlib import Path

import numpy as np
import pandas as pd

from src.analysis.aggregate import load_runs, summarise
from src.analysis.significance import compare, reference_interval

PLACEHOLDER = "\\textcolor{red}{??}"


class MacroSet:
    """Collects name/value pairs and writes them as \\newcommand definitions."""

    def __init__(self) -> None:
        self.values: dict[str, str] = {}

    def add(
        self, name: str, value, decimals: int = 4,
        percent: bool = False, signed: bool = False,
    ) -> None:
        """Format one number for the prose.

        ``signed`` forces an explicit plus on positive values, which is what a
        difference wants and an absolute score does not.
        """
        if value is None or (isinstance(value, float) and not np.isfinite(value)):
            self.values[name] = PLACEHOLDER
            return
        if isinstance(value, str):
            self.values[name] = value
            return
        number = 100 * float(value) if percent else float(value)
        formatted = f"{number:+.{decimals}f}" if signed else f"{number:.{decimals}f}"
        self.values[name] = formatted + ("\\%" if percent else "")

    def add_int(self, name: str, value) -> None:
        self.values[name] = PLACEHOLDER if value is None else f"{int(value):,}".replace(",", "{,}")

    def add_text(self, name: str, value: str) -> None:
        self.values[name] = value

    def write(self, path: Path) -> None:
        path.parent.mkdir(parents=True, exist_ok=True)
        lines = [
            "% Generated by src/analysis/macros.py. Do not edit by hand.",
            "% Every number quoted in the manuscript prose is defined here.",
            "",
        ]
        for name in sorted(self.values):
            lines.append(f"\\newcommand{{\\{name}}}{{{self.values[name]}}}")
        path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def _stat(summary: pd.DataFrame, arm: str, metric: str, kind: str) -> float | None:
    """One aggregated number, or None when that stage has not been run yet.

    A stage with no runs yields an empty frame with no columns at all, which is
    the normal state while a study is still in progress, so this returns None
    rather than raising and every dependent macro falls back to a placeholder.
    """
    column = f"{metric}_{kind}"
    if summary.empty or "arm" not in summary.columns or column not in summary.columns:
        return None
    row = summary[summary["arm"] == arm]
    if row.empty:
        return None
    value = row.iloc[0][column]
    return None if pd.isna(value) else float(value)


def _mean(summary: pd.DataFrame, arm: str, metric: str) -> float | None:
    return _stat(summary, arm, metric, "mean")


def _std(summary: pd.DataFrame, arm: str, metric: str) -> float | None:
    return _stat(summary, arm, metric, "std")


def build_paper1_macros(output: Path) -> MacroSet:
    macros = MacroSet()
    runs = load_runs(1)
    if runs.empty:
        macros.write(output)
        return macros

    metrics = ["auprc", "mcc", "f1", "precision", "recall", "roc_auc"]

    baselines = summarise(runs[runs["stage"] == "baselines"], metrics)
    for arm, prefix in (
        ("lightgbm", "LgbmBase"), ("random_forest", "RfBase"), ("xgboost", "XgbBase"),
        ("catboost", "CatBase"), ("logistic_regression", "LrBase"), ("mlp", "MlpBase"),
        ("cnn1d", "CnnBase"), ("bilstm", "LstmBase"), ("autoencoder", "AeBase"),
    ):
        macros.add(f"{prefix}AUPRC", _mean(baselines, arm, "auprc"))
        macros.add(f"{prefix}MCC", _mean(baselines, arm, "mcc"))
        macros.add(f"{prefix}FOne", _mean(baselines, arm, "f1"))

    if not baselines.empty and "auprc_mean" in baselines.columns:
        best_row = baselines.loc[baselines["auprc_mean"].idxmax()]
        macros.add_text("BestBaselineName", str(best_row["arm"]).replace("_", " "))
        macros.add("BestBaselineAUPRC", float(best_row["auprc_mean"]))

    sampling = summarise(runs[runs["stage"] == "sampling"], metrics)
    for arm, prefix in (
        ("lgbm_none", "SampNone"), ("lgbm_smote", "SampSmote"),
        ("lgbm_adasyn", "SampAdasyn"), ("lgbm_smote_tomek", "SampSmoteTomek"),
        ("lgbm_smote_enn", "SampSmoteEnn"), ("lgbm_borderline_smote", "SampBorderline"),
        ("lgbm_random_under", "SampUnder"), ("lgbm_random_over", "SampOver"),
        ("lgbm_tasr", "SampTasr"),
    ):
        macros.add(f"{prefix}AUPRC", _mean(sampling, arm, "auprc"))
        macros.add(f"{prefix}MCC", _mean(sampling, arm, "mcc"))

    tasr = _mean(sampling, "lgbm_tasr", "auprc")
    smote = _mean(sampling, "lgbm_smote", "auprc")
    if tasr is not None and smote is not None:
        macros.add("TasrOverSmote", tasr - smote)

    proposed = summarise(runs[runs["stage"] == "proposed"], metrics)
    for arm, prefix in (("proposed_lightgbm", "PropLgbm"), ("proposed_xgboost", "PropXgb")):
        macros.add(f"{prefix}AUPRC", _mean(proposed, arm, "auprc"))
        macros.add(f"{prefix}AUPRCStd", _std(proposed, arm, "auprc"))
        macros.add(f"{prefix}MCC", _mean(proposed, arm, "mcc"))
        macros.add(f"{prefix}FOne", _mean(proposed, arm, "f1"))
        macros.add(f"{prefix}Precision", _mean(proposed, arm, "precision"))
        macros.add(f"{prefix}Recall", _mean(proposed, arm, "recall"))

    best_proposed = _mean(proposed, "proposed_lightgbm", "auprc")
    best_base = None
    if not baselines.empty and "auprc_mean" in baselines.columns:
        best_base = float(baselines["auprc_mean"].max())
    if best_proposed is not None and best_base is not None:
        macros.add("ProposedGain", best_proposed - best_base)
        macros.add("ProposedGainPct", 100 * (best_proposed - best_base) / best_base, decimals=2)

    ablation = summarise(runs[runs["stage"] == "ablation"], metrics)
    for arm, prefix in (
        ("full", "AblFull"), ("no_tasr", "AblNoTasr"), ("no_encoder", "AblNoEncoder"),
        ("no_contrastive", "AblNoContrastive"), ("no_reconstruction", "AblNoRecon"),
        ("embedding_only", "AblEmbedOnly"), ("no_cleaning", "AblNoCleaning"),
        ("one_block", "AblOneBlock"), ("smote_instead_of_tasr", "AblSmoteSwap"),
    ):
        macros.add(f"{prefix}AUPRC", _mean(ablation, arm, "auprc"))

    full = _mean(ablation, "full", "auprc")
    for arm, prefix in (
        ("no_tasr", "AblNoTasr"), ("no_encoder", "AblNoEncoder"),
        ("no_contrastive", "AblNoContrastive"), ("no_reconstruction", "AblNoRecon"),
        ("embedding_only", "AblEmbedOnly"), ("no_cleaning", "AblNoCleaning"),
        ("one_block", "AblOneBlock"),
    ):
        value = _mean(ablation, arm, "auprc")
        macros.add(f"{prefix}Delta", None if (full is None or value is None) else value - full)

    leakage = summarise(runs[runs["stage"] == "leakage"], metrics)
    for arm, prefix in (
        ("chronological__in_fold", "LeakHonest"),
        ("chronological__before_split", "LeakChronoBefore"),
        ("random__in_fold", "LeakRandomInFold"),
        ("random__before_split", "LeakRandomBefore"),
    ):
        macros.add(f"{prefix}AUPRC", _mean(leakage, arm, "auprc"))
        macros.add(f"{prefix}MCC", _mean(leakage, arm, "mcc"))

    honest = _mean(leakage, "chronological__in_fold", "auprc")
    worst = _mean(leakage, "random__before_split", "auprc")
    if honest is not None and worst is not None:
        macros.add("LeakInflation", worst - honest)
        macros.add("LeakInflationPct", 100 * (worst - honest) / honest, decimals=1)

    folds = sorted(int(f) for f in runs["fold"].dropna().unique())
    interval = reference_interval(1, ("proposed", "proposed_lightgbm"), folds)
    if interval:
        macros.add("PooledAUPRC", interval["auprc"])
        macros.add("PooledCILow", interval["ci_low"])
        macros.add("PooledCIHigh", interval["ci_high"])
        macros.add_int("PooledSamples", interval["n_samples"])
        macros.add_int("PooledPositives", interval["n_positives"])

    comparators = [("baselines", "lightgbm"), ("baselines", "random_forest"),
                   ("sampling", "lgbm_smote")]
    for outcome in compare(1, ("proposed", "proposed_lightgbm"), comparators, folds):
        key = outcome.comparator.replace("_", "").title()
        macros.add(f"Vs{key}Delta", outcome.delta_auprc)
        macros.add(f"Vs{key}P", outcome.auprc_p)
        macros.add(f"Vs{key}DelongP", outcome.delong_p)

    # Stream sizes as published, verified against the cached copies by
    # scripts/describe_datasets.py. These are deliberately named apart from the
    # \<Stream>Frauds macros the feedback study emits: those count the frauds
    # falling inside the replayed window, which excludes the fully labelled
    # first round, so quoting one as the other understates the dataset.
    for name, rows, frauds in (("Baf", 1_000_000, 11_029),
                               ("Ieee", 590_540, 20_663),
                               ("Ulb", 284_807, 492)):
        macros.add_int(f"{name}TotalRows", rows)
        macros.add_int(f"{name}TotalFrauds", frauds)
        macros.add(f"{name}FraudRate", frauds / rows, decimals=2, percent=True)

    macros.add("UlbMinorityPct", 0.1727, decimals=4)
    _add_feedback_macros(macros)
    macros.write(output)
    return macros


# Short names for the arms, used to build macro names like \BafProposedCatch.
FEEDBACK_ARM_SLUGS = {
    "oracle_full_labels": "Oracle",
    "naive_assume_negative": "Naive",
    "reviewed_only": "Reviewed",
    "explore_uniform": "ExploreUniform",
    "explore_banded": "ExploreBanded",
    "soft_censor": "SoftCensor",
    "censor": "Censor",
    "censor_ips": "CensorIps",
    "ips": "Ips",
    "ips_augmented": "IpsAug",
    "explore_censor": "Proposed",
    "explore_soft_censor": "ProposedSoft",
}

FEEDBACK_DATASET_SLUGS = {
    "baf_base": "Baf",
    "baf_variant3": "BafThree",
    "ieee_cis": "Ieee",
    "ulb_creditcard": "Ulb",
}


def _add_feedback_macros(macros: MacroSet) -> None:
    """Numbers from the feedback study, per dataset and per arm.

    The prose leads on how much fraud each rule caught and how much of the
    oracle-to-practice gap it recovered, so those are emitted for every arm; the
    ranking metrics follow for the arms the discussion names.
    """
    from src.analysis.aggregate import load_feedback

    for stage, suffix in (("main", ""), ("robustness", "Rob")):
        frame = load_feedback(stage)
        if frame.empty:
            continue

        for dataset, subset in frame.groupby("dataset"):
            slug = FEEDBACK_DATASET_SLUGS.get(str(dataset))
            if slug is None:
                continue
            slug = f"{slug}{suffix}"

            means = subset.groupby("arm")[
                ["catch_rate", "auprc_mean", "auprc_final", "pool_error_rate",
                 "capacity_ratio", "frauds_caught", "frauds_present",
                 "review_precision", "reviews_spent"]
            ].mean()

            naive = means["catch_rate"].get("naive_assume_negative", np.nan)
            oracle = means["catch_rate"].get("oracle_full_labels", np.nan)
            gap = oracle - naive

            for arm, name in FEEDBACK_ARM_SLUGS.items():
                if arm not in means.index:
                    continue
                record = means.loc[arm]
                macros.add(f"{slug}{name}Catch", record["catch_rate"], decimals=2, percent=True)
                macros.add(f"{slug}{name}Auprc", record["auprc_mean"])
                macros.add(f"{slug}{name}AuprcFinal", record["auprc_final"])
                macros.add(f"{slug}{name}PoolError", record["pool_error_rate"],
                           decimals=3, percent=True)
                if np.isfinite(naive):
                    macros.add(f"{slug}{name}Delta",
                               record["auprc_mean"] - means["auprc_mean"].get(
                                   "naive_assume_negative", np.nan),
                               decimals=4, signed=True)
                if np.isfinite(gap) and abs(gap) > 1e-12:
                    macros.add(f"{slug}{name}Recovered",
                               (record["catch_rate"] - naive) / gap, decimals=0, percent=True)

            if np.isfinite(gap):
                macros.add(f"{slug}LoopCost", gap, decimals=2, percent=True)
                if np.isfinite(oracle) and oracle > 0:
                    macros.add(f"{slug}LoopCostRelative", gap / oracle, decimals=1, percent=True)

            if "frauds_present" in means.columns and len(means):
                macros.add_int(f"{slug}Frauds", means["frauds_present"].max())
            if "capacity_ratio" in means.columns and len(means):
                macros.add(f"{slug}Capacity", means["capacity_ratio"].max(), decimals=2)

            # Why training on the reviewed rows alone succeeds on two streams and
            # fails on the third. That pool carries no wrong labels by
            # construction, so what varies is whether it is enriched enough in
            # fraud to train on, or complete enough to stand for the fraud it
            # discarded. Both quantities are needed to order the three streams.
            if "reviewed_only" in means.index:
                record = means.loc["reviewed_only"]
                macros.add(f"{slug}ReviewPrecision", record["review_precision"],
                           decimals=0, percent=True)
                present = record["frauds_present"]
                if np.isfinite(present) and present > 0:
                    macros.add(f"{slug}ReviewedCoverage",
                               record["review_precision"] * record["reviews_spent"] / present,
                               decimals=0, percent=True)
                macros.add_int(f"{slug}ReviewedPool", record["reviews_spent"])
            macros.add_int(f"{slug}Rounds", subset["n_rounds"].dropna().max()
                           if subset["n_rounds"].notna().any() else None)
            macros.add_int(f"{slug}Seeds", subset["seed"].nunique())

    _add_capacity_macros(macros)


BASIS_POINT_WORDS = {10: "Ten", 20: "Twenty", 50: "Fifty",
                     100: "Hundred", 200: "TwoHundred"}


def _add_capacity_macros(macros: MacroSet) -> None:
    """How the censoring rules behave as analyst capacity grows.

    Censoring is the paper's recommendation, and the capacity sweep is where it
    stops working: on Bank Account Fraud the hard rule turns from the best
    remedy to a worse choice than doing nothing somewhere above half a review
    per fraud. The prose has to be able to name that point and the recoveries
    either side of it, so they are emitted per budget rather than summarised.
    """
    from src.analysis.aggregate import load_feedback

    frame = load_feedback("capacity")
    if frame.empty or "budget_fraction" not in frame.columns:
        return

    for budget, block in frame.groupby("budget_fraction"):
        means = block.groupby("arm")["catch_rate"].mean()
        naive = means.get("naive_assume_negative", np.nan)
        gap = means.get("oracle_full_labels", np.nan) - naive
        if not np.isfinite(gap) or abs(gap) < 1e-12:
            continue

        # A LaTeX control word is letters only, so the budget has to be spelled
        # out. These are basis points of transactions reviewed per round.
        points = round(float(budget) * 10_000)
        if points not in BASIS_POINT_WORDS:
            continue
        tag = f"Cap{BASIS_POINT_WORDS[points]}"
        macros.add(f"Baf{tag}Ratio", block["capacity_ratio"].mean(), decimals=2)
        macros.add(f"Baf{tag}GapRelative", gap / means["oracle_full_labels"],
                   decimals=1, percent=True)
        for arm, name in (("censor", "Censor"), ("soft_censor", "SoftCensor"),
                          ("explore_banded", "ExploreBanded")):
            if arm in means.index:
                macros.add(f"Baf{tag}{name}Recovered", (means[arm] - naive) / gap,
                           decimals=0, percent=True)


def build_paper2_macros(output: Path) -> MacroSet:
    macros = MacroSet()
    runs = load_runs(2)
    if runs.empty:
        macros.write(output)
        return macros

    metrics = ["roc_auc", "ks", "f1", "g_mean", "brier"]
    slugs = {"uci_dccc": "Dccc", "german_credit": "German", "give_me_some_credit": "Gmsc"}

    for dataset, frame in runs.groupby("dataset"):
        slug = slugs.get(str(dataset))
        if slug is None:
            continue
        summary = summarise(frame, metrics)
        for arm, prefix in (
            ("logistic_regression", "Lr"), ("random_forest", "Rf"), ("xgboost", "Xgb"),
            ("lightgbm", "Lgbm"), ("catboost", "Cat"), ("mlp", "Mlp"), ("svm", "Svm"),
            ("knn", "Knn"), ("tabnet_reference", "TabRef"), ("tabnet_vanilla", "TabVan"),
            ("gma_full", "Gma"), ("gma_single_head", "GmaOneHead"),
            ("gma_fixed_temperature", "GmaFixedTemp"),
            ("gma_no_interaction_gate", "GmaNoGate"), ("gma_no_focal", "GmaNoFocal"),
            ("gma_pretrained", "GmaPretrained"),
            ("stack_tabnet_vanilla", "StackVan"), ("stack_gma", "StackGma"),
            ("stack_no_extractor", "StackNone"),
        ):
            macros.add(f"{slug}{prefix}AUC", _mean(summary, arm, "roc_auc"))
            macros.add(f"{slug}{prefix}KS", _mean(summary, arm, "ks"))

        gma = _mean(summary, "gma_full", "roc_auc")
        vanilla = _mean(summary, "tabnet_vanilla", "roc_auc")
        if gma is not None and vanilla is not None:
            macros.add(f"{slug}GmaOverVanilla", gma - vanilla)

        pretrained = _mean(summary, "gma_pretrained", "roc_auc")
        if gma is not None and pretrained is not None:
            macros.add(f"{slug}PretrainGain", pretrained - gma)

        stack_gma = _mean(summary, "stack_gma", "roc_auc")
        stack_van = _mean(summary, "stack_tabnet_vanilla", "roc_auc")
        if stack_gma is not None and stack_van is not None:
            macros.add(f"{slug}StackGain", stack_gma - stack_van)

        best = None
        baseline_frame = summarise(frame[frame["stage"] == "baselines"], metrics)
        if not baseline_frame.empty and "roc_auc_mean" in baseline_frame.columns:
            best_row = baseline_frame.loc[baseline_frame["roc_auc_mean"].idxmax()]
            best = float(best_row["roc_auc_mean"])
            macros.add_text(f"{slug}BestBaselineName", str(best_row["arm"]).replace("_", " "))
            macros.add(f"{slug}BestBaselineAUC", best)
        if stack_gma is not None and best is not None:
            macros.add(f"{slug}ProposedGain", stack_gma - best)

    _add_hpo_macros(macros)
    _add_attribution_macros(macros)

    macros.add_int("DcccRows", 30_000)
    macros.add_int("GermanRows", 1_000)
    macros.add_int("GmscRows", 150_000)
    macros.write(output)
    return macros


def _add_attribution_macros(macros: MacroSet) -> None:
    """The leading feature under each attribution, and how well the two agree."""
    from src.analysis.interpret_report import load
    from src.paper2_credit.data import display_name

    slugs = {"uci_dccc": "Dccc", "german_credit": "German", "give_me_some_credit": "Gmsc"}

    for dataset, payload in load().items():
        slug = slugs.get(dataset)
        if slug is None:
            continue
        features = payload["features"]
        shap = np.asarray(payload["shap_share"], dtype=float)
        mask = np.asarray(payload["mask_share"], dtype=float)

        top_shap = int(np.argmax(shap))
        top_mask = int(np.argmax(mask))
        macros.add_text(
            f"{slug}TopShapFeature",
            "\\texttt{" + display_name(dataset, features[top_shap]).replace("_", "\\_") + "}",
        )
        macros.add_text(
            f"{slug}TopAttnFeature",
            "\\texttt{" + display_name(dataset, features[top_mask]).replace("_", "\\_") + "}",
        )
        macros.add(f"{slug}TopShapShare", shap[top_shap], decimals=1, percent=True)
        macros.add(f"{slug}TopAttnShare", mask[top_mask], decimals=1, percent=True)
        macros.add(f"{slug}AttnRho", payload["spearman"], decimals=2)

        # How concentrated each mechanism is: the share carried by five features.
        macros.add(f"{slug}ShapTopFive", float(np.sort(shap)[::-1][:5].sum()),
                   decimals=0, percent=True)
        macros.add(f"{slug}AttnTopFive", float(np.sort(mask)[::-1][:5].sum()),
                   decimals=0, percent=True)


def _add_hpo_macros(macros: MacroSet) -> None:
    import json

    from src.common.io import PROJECT_ROOT

    directory = PROJECT_ROOT / "results" / "paper2" / "tuning"
    if not directory.exists():
        return

    slugs = {"uci_dccc": "Dccc", "german_credit": "German", "give_me_some_credit": "Gmsc"}
    # Two spellings of the same four optimisers: one that can be part of a macro
    # name, which has to be letters only, and one for running text, where TPE
    # and PSO are acronyms and reading "Pso" in a sentence is a defect.
    names = {"random": "Random", "tpe": "Tpe", "pso": "Pso", "ga": "Ga"}
    labels = {"random": "random search", "tpe": "TPE", "pso": "PSO",
              "ga": "the genetic algorithm"}

    per_dataset: dict[str, dict[str, dict]] = {}
    for path in sorted(directory.glob("*__hpo__*.json")):
        payload = json.loads(path.read_text(encoding="utf-8"))
        per_dataset.setdefault(payload.get("dataset", ""), {})[payload["optimiser"]] = payload

    for dataset, studies in per_dataset.items():
        slug = slugs.get(dataset)
        if slug is None:
            continue
        for optimiser, payload in studies.items():
            prefix = f"{slug}Hpo{names.get(optimiser, optimiser.title())}"
            macros.add(f"{prefix}Best", payload.get("best_value"))
            macros.add_int(f"{prefix}Evals", payload.get("n_evaluations"))
        if studies:
            winner = max(studies, key=lambda k: studies[k].get("best_value", -1))
            macros.add_text(f"{slug}HpoWinner", labels.get(winner, winner))
            # The winner's own score, so the prose can quote it without naming
            # an optimiser that a rerun might demote.
            macros.add(f"{slug}HpoWinnerBest", studies[winner].get("best_value"))
            budget = next(iter(studies.values())).get("budget_seconds")
            if budget:
                macros.add_int(f"{slug}HpoBudget", int(budget))
